dist: bionic
language: python
services:
  - xvfb

matrix:
    include:
        - os: linux
          env: PYTHON_VERSION=3.8

before_install:
  - wget -q http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - sudo apt-get install octave
install:
    - conda create -n testenv --yes python=${PYTHON_VERSION}
    - source activate testenv
    - conda install --yes --quiet numpy matplotlib numexpr scipy
    - pip install flake8 check-manifest
    - pip install nose coverage
    - python setup.py install
script:
    - make
    - flake8 --count picard
    - cd examples/matlab_octave
    - octave plot_ica.m
    - octave plot_ica_whiten.m
    - octave plot_ica_pca.m
    - cd ..//..
after_success:
  - bash <(curl -s https://codecov.io/bash)
